#!/bin/bash
cont_count=$1
echo "creating $cont_count containers.."
sleep 2;
for i in `seq $cont_count`
do
	echo "=============================="
    echo "Creating www.shell$i container.."
    sleep 1
   sudo docker run --name www.shell$i -d -it --rm mano8888/nginx /bin/bash
    echo "www.shell$i container has been created!"
	echo "=============================="
done
