deploy:deploy_file
-DgroupId=com.file
-DartifactId=file
-Dversion=1.0-SNAPSHOT
-Dpackaging=war
-DgeneratePom=false
-Drepositorty=nexus
-Durl=https://nexus-tb-file.com/repository/some_pro
-Dfile=1.0_SNAPSHOT.war
